name: Automated Security Scan and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Manual trigger option

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Docker Buildx for building the image
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:${{ github.sha }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:latest .

      # Set up Trivy
      - name: Set Up Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.tar.gz
          tar zxvf trivy_0.50.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version

      # Scan the image for vulnerabilities (fail if HIGH/CRITICAL found)
      - name: Scan Docker Image with Trivy
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 \
          ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:${{ github.sha }} | tee trivy-scan.log

      # Generate Trivy report (always, even if scan fails)
      - name: Generate Trivy Report
        if: always()
        run: |
          trivy image --format json -o trivy-report.json \
          ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:${{ github.sha }}

      # Upload Trivy report and scan log as artifacts
      - name: Upload Trivy Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-artifacts
          path: |
            trivy-report.json
            trivy-scan.log

      # Push to Docker Hub only if scan passes
      - name: Push Docker Image to Docker Hub
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:latest
