name: Automated Security Scan and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Manual trigger option

env:
  IMAGE_NAME: sohelqt8797/trivy-security-demo
  FAIL_ON_VULNERABILITIES: true

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the base Docker image
      - name: Build Base Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:base-${{ github.sha }} .
        # Fail the workflow if build fails
        continue-on-error: false

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.tar.gz
          tar zxvf trivy_0.50.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version || { echo "Trivy installation failed"; exit 1; }
        # Fail the workflow if Trivy installation fails
        continue-on-error: false

      # Scan the image for vulnerabilities