name: Automated Security Scan and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Manual trigger option

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Docker Buildx for building the image
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image with both :latest and :sha tags
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:${{ github.sha }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:latest

      # Set up Trivy
      - name: Set Up Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.50.1/trivy_0.50.1_Linux-64bit.tar.gz
          tar zxvf trivy_0.50.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version

      # Scan the image for vulnerabilities (fail if HIGH/CRITICAL found)
      - name: Scan Docker Image with Trivy
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 \
          ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:${{ github.sha }}

      # Generate Trivy report (always, even if scan fails)
      - name: Generate Trivy Report
        if: always()
        run: |
          trivy image --format json -o trivy-report.json \
          ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:${{ github.sha }}

      # Upload Trivy report as artifact
      - name: Upload Trivy Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-report.json

      # Send Slack alert on failure (optional)
      - name: Send Slack Alert on Failure
        if: failure() && secrets.SLACK_WEBHOOK_URL
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "⚠️ *Security Scan Failed!* High/Critical vulnerabilities found in ${{ secrets.DOCKER_USERNAME }}/trivy-security-demo:${{ github.sha }}. Check GitHub Actions for details."
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
